// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 19/08/2026, 21:39:42
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/Micro/Desktop/Projeto/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Micro/Desktop/Projeto/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Micro/Desktop/Projeto/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Micro/Desktop/Projeto/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Micro/Desktop/Projeto/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/Micro/Desktop/Projeto/frontend/composables/**/*.{js,ts,mjs}","C:/Users/Micro/Desktop/Projeto/frontend/utils/**/*.{js,ts,mjs}","C:/Users/Micro/Desktop/Projeto/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Micro/Desktop/Projeto/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Micro/Desktop/Projeto/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Micro/Desktop/Projeto/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;