<template><PublicPage eyebrow="Produto" title="Tudo o que sua equipe precisa para entregar" description="Um espaço único para planejar, acompanhar e conversar sobre o trabalho.">
  <div class="mb-8 flex flex-wrap gap-3 text-sm text-[color:var(--text-muted)] items-center justify-center">
    <span class="rounded-full border border-[color:var(--border)] bg-[color:var(--surface)] px-4 py-2">Planejamento e execução</span>
    <span class="rounded-full border border-[color:var(--border)] bg-[color:var(--surface)] px-4 py-2">Projetado para clareza</span>
    <span class="rounded-full border border-[color:var(--border)] bg-[color:var(--surface)] px-4 py-2">Colaboração em tempo real</span>
  </div>
  <div class="grid gap-5 sm:grid-cols-2"><article v-for="item in features" :key="item.title" class="group rounded-3xl border border-[color:var(--border)] bg-[color:var(--surface)]/80 p-7 backdrop-blur"><div class="mb-8 flex h-12 w-12 items-center justify-center rounded-2xl bg-[color:var(--accent-soft-bg)] text-[color:var(--primary)] transition group-hover:scale-110"><Icon :name="item.icon" :size="22" /></div><h2 class="text-xl font-semibold">{{ item.title }}</h2><p class="mt-3 max-w-sm leading-7 text-[color:var(--text-muted)]">{{ item.text }}</p><span class="mt-7 inline-flex text-sm font-semibold text-[color:var(--text-info)]">Saiba mais <span class="ml-2 transition group-hover:translate-x-1" aria-hidden="true">→</span></span></article></div>
</PublicPage></template>
<script setup lang="ts">definePageMeta({ layout: 'public' }); const features: Array<{ icon: 'layers' | 'message' | 'chart' | 'bolt'; title: string; text: string }> = [{ icon:'layers', title:'Projetos e prioridades', text:'Organize objetivos, tarefas e responsáveis sem perder o contexto.' }, { icon:'message', title:'Conversa no contexto', text:'Decisões ficam perto do trabalho, para todos avançarem na mesma direção.' }, { icon:'chart', title:'Visão da operação', text:'Acompanhe progresso e gargalos com informações claras e atualizadas.' }, { icon:'bolt', title:'Fluxo sem atrito', text:'Menos troca de abas e mais tempo para executar o que realmente importa.' }]</script>
